version: '3'

services: 
  app:
    build: .
    container_name: flask-docker-app
    command: python app.py
    ports: 
      - "5000:5000"
    volumes:
      - .:/app
    depends_on: 
      - db
  db:
    image: postgres
    container_name: flask-docker-db
    tty: true
    environment:
      - POSTGRES_DB=flask_docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - flask-docker-pgdata:/var/lib/postgresql/data

volumes:
  flask-docker-pgdata: